---
- hosts: all
  remote_user: ubuntu
  vars:
    java_version: 'jdk-11.0.5+10'
    java_install_dir: '/opt/java'
    tomcat_java_home: "/opt/java/jdk-11.0.5/"
    #tomcat_archive_name: "apache-tomcat-9.0.34"
    #tomcat_use_local_archive: true
    #tomcat_redis_filename: apache-tomcat-9.0.34.tar.gz

  roles:
    - gantsign.java
    - {role: ansible-role-tomcat}
